# Workflow name
name: "Chromatic Deployment"

# Event for the workflow
on: push

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: yarn
        #👇 Adds Chromatic as a step in the workflow
      - uses: chromaui/action@v1
        # Options required for Chromatic's GitHub Action
        with:
          #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/en/deploy/ to obtain it
<<<<<<< HEAD
          projectToken: ${{ secrets.process.env.REACT_APP_CHROMATIC_PROJECT_TOKEN }}
=======
          projectToken: ${{ secrets.chpt_b90e601a9d20f37 }}
>>>>>>> d823b982021231cb51780ef1effeeb13bd221dc5
          token: ${{ secrets.GITHUB_TOKEN }}
